<a href="https://colab.research.google.com/github/rriyaram/Analyzing-E-Learning-Platform-purchases/blob/main/PythonDA_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Analysis using

NumPy and Pandas

Create a 1D NumPy Array:

In [94]:
import numpy as np

In [ ]:
temperatures_w1=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])
temperatures_w1

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])

Inspection and Properties:

In [ ]:
temperatures_w1.ndim

2

In [ ]:
temperatures_w1.shape

(1, 7)

In [ ]:
temperatures_w1.size

7

In [ ]:
temperatures_w1.dtype


dtype('float64')

Array Operations:

In [ ]:

fahrenheit = (temperatures_w1 * 9/5) + 32
fahrenheit


array([[72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42]])

In [ ]:
np.min(temperatures_w1)

np.float64(20.8)

In [ ]:
np.max(temperatures_w1)

np.float64(26.1)

In [ ]:
np.mean(temperatures_w1)

np.float64(23.542857142857144)

Array Slicing and Indexing:

Extract the temperatures for the first three days of the week.

In [ ]:
fahrenheit[:, :3]

array([[72.5 , 77.54, 69.44]])

Extract the temperatures for the weekend (last two days).

In [ ]:
fahrenheit[:, -2:]

array([[76.64, 71.42]])

Extract the temperatures for the middle three days of the week.

In [ ]:
fahrenheit[0,2:5]

array([69.44, 74.12, 78.98])

Create a 2D Array:

In [4]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                      [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

Inspect and Slice the 2D Array:

In [5]:
temperatures.shape

(2, 7)

In [7]:
temperatures.dtype

dtype('float64')

In [8]:
temperatures.size

14

Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [10]:
temperatures[:,5:7]

array([[24.8, 21.9],
       [22.8, 20.1]])

Pandas Series:

In [38]:
import pandas as pd

In [60]:
Marks=pd.Series([95, 92, 89, 85, 80],
    index= ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'],name='Marks')
Marks

,Marks
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


Indexing and Slicing:

In [61]:
Marks[0]

/tmp/ipython-input-2988554515.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Marks[0]


np.int64(95)

In [64]:
top_3_marks = Marks.loc[['Rank1', 'Rank2', 'Rank3']]
print(top_3_marks)

Rank1    95
Rank2    92
Rank3    89
Name: Marks, dtype: int64


In [65]:
Marks.iloc[2]

np.int64(89)

Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [67]:
mask = Marks > 90
print(mask)

Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
Name: Marks, dtype: bool


Manipulating Series:

Modify the mark of the student with the 1st rank to 100.

Remove the entry corresponding to the last rank from the Series.

In [71]:
Marks.loc['Rank1'] = 100
Marks

,Marks
Rank1,100
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [72]:
marks_series = Marks.drop('Rank5')
print(marks_series)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: Marks, dtype: int64


In [74]:
Marks.drop('Rank5', inplace=True)

Compute the CGPA by dividing each mark in the Series by 10.

In [75]:
cgpa_series = Marks/ 10
print(cgpa_series)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Name: Marks, dtype: float64


Pandas DataFrame:

In [110]:
transactions=pd.DataFrame({"TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
              "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture',
              'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
              "Region": ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
              'South', 'North'],
              "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [115]:
df=pd.DataFrame(transactions).set_index('TransactionID')
df

,ProductCategory,Region,Amount
TransactionID,,,
101,Electronics,North,200
102,Clothing,South,150
103,Electronics,North,300
104,Furniture,East,450
105,Clothing,West,200
106,Electronics,North,250
107,Furniture,East,300
108,Clothing,West,180
109,Furniture,South,350


Data Exploration:

In [52]:
df.head()

,ProductCategory,Region,Amount
TransactionID,,,
101,Electronics,North,200
102,Clothing,South,150
103,Electronics,North,300
104,Furniture,East,450
105,Clothing,West,200


In [53]:
df.tail()

,ProductCategory,Region,Amount
TransactionID,,,
106,Electronics,North,250
107,Furniture,East,300
108,Clothing,West,180
109,Furniture,South,350
110,Electronics,North,400


In [55]:
df.shape

(10, 3)

In [56]:
df.columns

Index(['ProductCategory', 'Region', 'Amount'], dtype='object')

In [76]:
df = pd.DataFrame(transactions)
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


Display only the 'ProductCategory' and 'Amount' columns.

In [77]:
df[['ProductCategory','Amount']]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


Retrieve the last 3 columns of the DataFrame

In [81]:
df[df.columns[-3:]]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [82]:
df[(df['Region'] == 'North') & (df['Amount'] > 200)]

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


Find the value counts for the 'ProductCategory' column.

In [84]:
df['ProductCategory'].value_counts()

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


Find the unique values in the 'Region' column.

In [85]:
df['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

Group by 'Region' and find the mean amount for each region.

In [87]:
df.groupby("Region")['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


3. Manipulating the DataFrame:

In [ ]:
Index(['TransactionID', 'Customer', 'Amount'], dtype='object')

Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [102]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 160
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,160
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [121]:
df['Discount'] = df['Amount'] * 0.10
df

,ProductCategory,Region,Amount,Discount
TransactionID,,,,
101,Electronics,North,200,20.0
102,Clothing,South,150,15.0
103,Electronics,North,300,30.0
104,Furniture,East,450,45.0
105,Clothing,West,200,20.0
106,Electronics,North,250,25.0
107,Furniture,East,300,30.0
108,Clothing,West,180,18.0
110,Electronics,North,400,40.0


Remove the row with TransactionID 109.

In [116]:
df.drop(109, inplace=True)
df

,ProductCategory,Region,Amount
TransactionID,,,
101,Electronics,North,200
102,Clothing,South,150
103,Electronics,North,300
104,Furniture,East,450
105,Clothing,West,200
106,Electronics,North,250
107,Furniture,East,300
108,Clothing,West,180
110,Electronics,North,400


Delete the 'Discount' column from the DataFrame.

In [122]:
df.drop('Discount', axis=1, inplace=True)
df

,ProductCategory,Region,Amount
TransactionID,,,
101,Electronics,North,200
102,Clothing,South,150
103,Electronics,North,300
104,Furniture,East,450
105,Clothing,West,200
106,Electronics,North,250
107,Furniture,East,300
108,Clothing,West,180
110,Electronics,North,400
